### ISSUE TITLE
Error when attempting to turn on "Paint mode"

### ISSUE THREAD

**Issue by Septem151** [Bram91/Brush-Markers#2]
I'm unable to paint tiles and the plugin is unusable. Here's the error from the client logs:
```
java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @7d42c224
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at com.google.gson.Gson.toJson(Gson.java:683)
	at com.google.gson.Gson.toJson(Gson.java:638)
	at com.google.gson.Gson.toJson(Gson.java:618)
	at com.bram91.brushmarkers.BrushMarkerPlugin.savePoints(BrushMarkerPlugin.java:114)
	at com.bram91.brushmarkers.BrushMarkerPlugin.onClientTick(BrushMarkerPlugin.java:406)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:189)
	at client.lx(client.java:6779)
	at client.fp(client.java:3569)
	at client.ax(client.java:1349)
	at aj.d(aj.java:377)
	at aj.run(aj.java:356)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Can provide more information if needed.

**Comment by Septem151** [comment]
Issue occurs when using JDK 17. Does not occur when using JDK 11.
Related to an issue with GSON as described in this similar issue: https://github.com/ATLauncher/ATLauncher/issues/465

**Comment by jefehlab** [comment]
is there any plan to fix this? It won't work for me either.
